config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    if Rails.env == "production"
	    request.subdomain.present?
    elsif Rails.env == "staging"
      request.subdomain.present?
    else
      request.subdomain.gsub!(".demo-alokrawat050","").present?
	  end
  end
end

class SubdomainBlank
  def self.matches?(request)
    if Rails.env == "production"
	    request.subdomain.blank?
    elsif Rails.env == "staging"
      request.subdomain.blank?
    else
      request.subdomain.gsub!(".dmeo-alokrawat050","").blank?
	  end
  end
end

Rails.application.routes.draw do
  get 'plans/index'
  constraints(SubdomainPresent) do 
    root 'home#index', as: :subdomain_root
    devise_for :users,
    controllers: { invitations: 'users/invitations' }
    resources :invite_users
    resources :users#, only: :index
    resources :payments, only: [:new, :create]
    resources :plans, only: [:index]
    resources :clients
    resources :data_imports do 
      collection { post :export_to_xml }
    end
    get 'form_infos/index'
    get 'form_infos/multiple_gstin'
    post 'form_infos/gstin_selection'
  end  
  
  constraints(SubdomainBlank) do 
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
    resources :welcome do
      collection { post :find_team
      post :send_customer_mail
      get :find_team_index}
    end
  end  

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :plan
  belongs_to :company_master
  #validates_presence_of :plan_id
  #validates_presence_of :email
  
  #attr_accessor :stripe_card_token
  
  def save_with_payment
    if valid?
        customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
        self.stripe_customer_token = customer.id
        save!
    end
    rescue Stripe::InvalidRequestError => e
        logger.error "Stripe error while creating customer: #{e.message}"
        errors.add :base, "There was a problem with your credit card."
        false
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :authenticate_user!
  # GET /payments/new
  def new
    #plan = Plan.find(params[:plan_id])
    #@payment = plan.payments.build
    @payment = Payment.new
  end

  def create
    if stripe_token = params[:stripe_token]
      if current_user.do_deposit_transaction(params[:payment_type], stripe_token)
        @payment = Payment.new
        #current_account.id, refer in the application_controller.rb, method name: current_account
        @payment.assign_attributes(:account_id => current_account.id, :created_by => current_user.username)
          if @payment.save
            flash[:notice] = 'Card charged successfully'
          end
      else
        flash[:alert] = 'Some error happened while charging you, please double check your card details'
      end
    else
      flash[:alert] = 'You did not submit the form correctly'
    end

    redirect_to root_path #new_payment_path
  end
  
  private
    def payment_params
      params.require(:payment).permit(:account_id)
    end
    
    def find_company_info
      @payment = Payment.find(params[:id])
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_tag payments_path, id: 'card-details' do |f| %>
<section id="download">
  <div class="container">
    <div class="row">  
      <div class="col-md-6 col-md-offset-3 well">
        <h1>Payment Details</h1>
        <div class="payment-errors"></div>
        <div>
          <label for="card-number">Card Number:</label>
          <input id="card-number" type="text" data-stripe="number" class="form-control card__input card__input_number" name="card_name" placeholder="9999 9999 9999 9999" />
           <!--pattern="[0-9]{14,23}"-->
        </div>
      
        <div>
          <label for="card-exp-month">Card Expiry Month:</label>
          <input id="card-exp-month" type="text" data-stripe="exp_month" class="form-control" placeholder="MM" />
          <%#= select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card-exp-month"} %>
          <%#= select_month nil, {add_month_numbers_true: true}, date: {name: nil, id: "card-exp-month", class: "form-control", stripe: "exp_month"}  %>
        </div>
      
        <div>
          <label for="card-exp-year">Card Expiry Year:</label>
          <input id="card-exp-year" type="text" data-stripe="exp_year" class="form-control" placeholder="YYYY" />
          <%#= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card-exp-year"}%>
          <%#= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card-exp-year", class: "form-control"}%>
        </div>
      
        <div>
          <label for="card-cvc">CVC:</label>
          <input id="card-cvc" type="text" data-stripe="cvc" class="form-control" placeholder="CVC" />
        </div>
      
        <div>
          <label for="payment-type">Payment Type:</label>
          <select id="payment-type" name="payment_type" class="form-control" >
            <option value="deposit">¥20 Deposit</option>
            <option value="subscription">Monthly subscription, ¥9.97</option>
          </select>
        </div>
        <div>
          <input type="submit" value="Pay Now" class="btn btn-success btn-block btn-lg" />
        </div>
      </div>
    </div>
  </div>
</section>  
<% end %>
<%= stripe_javascript_tag %>
<%= javascript_include_tag 'custom/payments.js', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'custom/vanilla-masker.min.js', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'custom/vanilla-masker.js', 'data-turbolinks-track' => true %>

<script>
$(function(){

// #maskNumber
	VMasker(document.getElementById("card-number")).maskNumber();
	VMasker(document.getElementById("card-exp-month")).maskNumber();
	VMasker(document.getElementById("card-exp-year")).maskNumber();
	VMasker(document.getElementById("card-cvc")).maskNumber();
	
	// #maskPattern
  VMasker(document.getElementById("card-number")).maskPattern('9999 9999 9999 9999');
	VMasker(document.getElementById("card-exp-month")).maskPattern('99');
	VMasker(document.getElementById("card-exp-year")).maskPattern('9999');
	VMasker(document.getElementById("card-cvc")).maskPattern('999');
	
// 	const cardNumber = document.getElementById('card__input_number');
//   cardNumber.addEventListener('input', (event) => {
//     const number = event.target.value;
  
//     if (number.length >= 14) {
//       const isLuhnCheckPassed = luhn(number.split(' ').join(''));
//       cardNumber.classList.toggle('card__input_invalid', !isLuhnCheckPassed);
//       cardNumber.classList.toggle('card__input_valid', isLuhnCheckPassed);
//     } else {
//       cardNumber.classList.remove('card__input_invalid', 'card__input_valid');
//     }
//   });
});
</script>

app/views/payments/new.html.erb
<%= render 'form' %>

app/views/payments/test.html.erb
<h1>Signing up for "<%= @subscription.plan.name %>"</h1>
<p>Includes <strong><%= @subscription.plan.kisses %> llama kisses</strong> for only <strong><%= number_to_currency @subscription.plan.price %></strong> per month!</p>

<%= form_for @subscription do |f| %>
  <% if @subscription.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :plan_id %>

  <%= f.hidden_field :stripe_card_token %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <% if @subscription.stripe_card_token.present? %>
    Credit card has been provided.
  <% else %>
    <div class="field">
      <%= label_tag :card_number, "Credit Card Number" %>
      <%= text_field_tag :card_number, nil, name: nil %>
    </div>
    <div class="field">
      <%= label_tag :card_code, "Security Code on Card (CVV)" %>
      <%= text_field_tag :card_code, nil, name: nil %>
    </div>
    <div class="field">
      <%= label_tag :card_month, "Card Expiration" %>
      <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
      <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
    </div>
  <% end %>
  <div id="stripe_error">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
  <div class="actions">
    <%= f.submit "Subscribe" %>
  </div>
<% end %>