config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    if Rails.env == "production"
	    request.subdomain.present?
    elsif Rails.env == "staging"
      request.subdomain.present?
    else
      request.subdomain.gsub!(".demo-alokrawat050","").present?
	  end
  end
end

class SubdomainBlank
  def self.matches?(request)
    if Rails.env == "production"
	    request.subdomain.blank?
    elsif Rails.env == "staging"
      request.subdomain.blank?
    else
      request.subdomain.gsub!(".dmeo-alokrawat050","").blank?
	  end
  end
end

Rails.application.routes.draw do
  get 'plans/index'
  constraints(SubdomainPresent) do 
    root 'home#index', as: :subdomain_root
    devise_for :users,
    controllers: { invitations: 'users/invitations' }
    resources :invite_users
    resources :users#, only: :index
    resources :payments, only: [:new, :create]
    resources :plans, only: [:index]
    resources :clients
    resources :data_imports do 
      collection { post :export_to_xml }
    end
    get 'form_infos/index'
    get 'form_infos/multiple_gstin'
    post 'form_infos/gstin_selection'
  end  
  
  constraints(SubdomainBlank) do 
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
    resources :welcome do
      collection { post :find_team
      post :send_customer_mail
      get :find_team_index}
    end
  end  

end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :payments
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    #@plans = Plan.order("price")
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<div id="plans">
  <h1>New Plan</h1>
  <% @plans = Plan.order("price") %>
  <% @plans.each do |plan| %>
    <div class="plan">
      <div class="name"><%= plan.name %></div>
      <div class="details">
        <div class="price">
          <%= number_to_currency plan.price, :precision => 0 %>
        </div>
        <div class="per_month">per month</div>
        <div class="users"><%= plan.users %> User</div>
        <div class="per_month">per month</div>
        <div class="signup">
          <%= link_to "Subscribe", new_account_path(:plan_id => plan.id) %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

app/views/plans/index.html.erb
<%= render 'form' %>